### ISSUE TITLE
not able to do google sign in 

### ISSUE THREAD

**Issue by s1998b** [verzac/taste-buddy#1]
I Have connected this app with my firebase but it is not doing google sign in can you please help me.

**Comment by verzac** [comment]
Hiya, apologies for the late response.

Unfortunately, I am no longer maintaining this repo (plus, this project was made two years ago, so I can't really remember details about it).

That being said, try getting a new web API key from the Firebase/Google console and put it in https://github.com/verzac/taste-buddy/blob/master/app/src/main/res/values/strings.xml (under default_web_client_id_google). This is because it's currently using my API key, which I think I have locked down/deleted.
